name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build Applications
        run: |
          npm run build:student
          npm run build:parent
      
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYPHANTOMDEV }}'
          
      - name: Deploy to Live Channel
        run: npx firebase-tools deploy --only hosting:myphantomdev,hosting:myphantom-students,hosting:myphantom-parent --project myphantomdev