name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYPHANTOMDEV }}'
      - name: 🔍 Verify .firebaserc
        run: cat .firebaserc
      - name: Deploy Preview to Firebase Hosting
        run: npx firebase-tools hosting:channel:deploy pr-${{ github.event.number }} --expires 7d --project myphantomdev --only myphantomdev